 CREATE TABLE users (
     userid  VARCHAR  UNIQUE PRIMARY KEY NOT NULL,
     name VARCHAR NOT NULL,
     score INTEGER NOT NULL DEFAULT 0,
     one BOOLEAN DEFAULT NULL,
     two BOOLEAN DEFAULT NULL,
     three BOOLEAN DEFAULT NULL,
     four BOOLEAN DEFAULT NULL,
     five BOOLEAN DEFAULT NULL,
     six BOOLEAN DEFAULT NULL,
     seven BOOLEAN DEFAULT NULL
)
